# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: maven:3.3.9

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.     
          - mvn --version
          - mvn sortpom:verify
          - mvn -X -e -T 1C -B clean package
          - mvn -B versions:display-dependency-updates
